### PR TITLE
MGMT-17871: Include proxy when computing openshift-apiserver spec-hash

### PR DESCRIPTION
**Pull request by mresvanis**
This PR includes the [proxy env vars](https://github.com/openshift/cluster-openshift-apiserver-operator/blob/release-4.16/pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go#L401-L404) to the [openshift-apiserver](https://github.com/openshift/cluster-openshift-apiserver-operator/blob/release-4.16/bindata/v3.11.0/openshift-apiserver/deploy.yaml) deployment JSON spec when [computing](https://github.com/openshift/cluster-openshift-apiserver-operator/blob/release-4.16/pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go#L350-L442) its [spec-hash annotation](https://github.com/openshift/library-go/blob/master/pkg/operator/resource/resourceapply/apps.go#L53), in order to skip an `openshift-apiserver` [rollout](https://github.com/openshift/library-go/blob/master/pkg/operator/resource/resourceapply/apps.go#L72-L101) after a recert run when the cluster-wide OCP `Proxy` is defined.

### CODE REVIEW

**Comment by omertuc** [comment]
Does this interact correctly with our Proxy rename feature? e.g. things like should it happen before or after the proxy rename. Maybe it already does, did not give a thorough review

**Comment by mresvanis** [comment]
> Does this interact correctly with our Proxy rename feature? e.g. things like should it happen before or after the proxy rename. Maybe it already does, did not give a thorough review

Yes, both the `openshift-apiserver` and the `oauth-apiserver` [spec-hash annotation adjustments](https://github.com/rh-ecosystem-edge/recert/blob/main/src/ocp_postprocess.rs#L62-L88) are triggered after [all the other customizations](https://github.com/rh-ecosystem-edge/recert/blob/main/src/ocp_postprocess.rs#L60).

**Comment by mresvanis** [comment]
@omertuc FYI, because our CI currently doesn't support recert's proxy rename feature (it already checks though that after recert the SNO is healthy and no control-plane rollouts are issued), I have manually tested e2e this change by:

- creating a seed with cluster-wide proxy
- creating a seed image
- creating a target with its own cluster-wide-proxy
- running a full IBU flow
- verifying that 
  1. the SNO is healthy and no control-plane rollouts are issued 2. that no new `openshift-apiserver` generation was issued

**Comment by eranco74** [comment]
@mresvanis do we need to cherry-pick this to the release branches?
```
git show-branch origin/main origin/release-4.16 origin/release-4.15 
! [origin/main] Merge pull request #156 from omertuc/timefix
 ! [origin/release-4.16] Merge pull request #155 from mresvanis/update-oauth-apiserver-deployment-spec
  ! [origin/release-4.15] Merge pull request #155 from mresvanis/update-oauth-apiserver-deployment-spec
---
-   [origin/main] Merge pull request #156 from omertuc/timefix
+   [origin/main^2] Fix type inference regression in indirect dependency
+   [origin/main^^2] Include proxy when computing openshift-apiserver spec-hash
--- [origin/release-4.16] Merge pull request #155 from mresvanis/update-oauth-apiserver-deployment-spec

```

**Pull request merged**
