### PR TITLE
Support proxy change in clusters without storage

### PR DESCRIPTION
**Pull request by omertuc**
We had a too strict condition, see diff comment

Prevents the follow error:

```
Caused by:
    0: performing ocp specific post-processing
    1: renaming proxy
    2: renaming all
    3: renaming etcd resources
    4: fixing storages
    5: no "/kubernetes.io/operator.openshift.io/storages/cluster"
: exit status 1
```

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by omertuc** [comment]
Forced push for formatting

**Comment by omertuc** [comment]
/override pull-ci-rh-ecosystem-edge-recert-main-e2e-aws-ovn-single-node-recert-parallel

**Pull request merged**
